---
# This playbook deploys the whole application stack in this site.


- name: configure and deploy Appache and PHP
  hosts: mariadb
  remote_user: root

  roles:
    - web

- name: deploy Mariadb and configure the databases
  hosts: mariadb
  remote_user: root

  roles:
    - db

- name: deploy myphpadmin
  hosts: mariadb
  remote_user: root

  roles:
    - myphpadmin


